version: '3.8'

services:
  voice-embedding-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Cache transformers models to avoid re-downloading
      - model_cache:/home/appuser/.cache/huggingface
      # Optional: Mount audio files directory
      - ./audio_files:/app/audio_files:ro
    environment:
      - TRANSFORMERS_CACHE=/home/appuser/.cache/huggingface
      - HF_HOME=/home/appuser/.cache/huggingface
      - TOKENIZERS_PARALLELISM=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    networks:
      - voice-embedding-network

  # Optional: Redis for caching embeddings
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - voice-embedding-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - voice-embedding-api
    restart: unless-stopped
    networks:
      - voice-embedding-network

volumes:
  model_cache:
    driver: local
  redis_data:
    driver: local

networks:
  voice-embedding-network:
    driver: bridge